services:
  postgres:
    image: postgres:17
    container_name: piazza-postgres-dev
    environment:
      POSTGRES_DB: piazza_virtuale_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.1
    container_name: piazza-redis-dev
    ports:
      - "6379:6379"

volumes:
  postgres_data:
